defaults:
  - classincremental

_target_: ACIL.model.classincremental.KFoldModel

steps: [None, 0]
reload_model_on_new_classes: True
query: True
kfold:
  _target_: sklearn.model_selection.KFold
  n_splits: 5
  shuffle: True
  random_state: ${seed}